apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: fullstack
spec:
  ports:
  - port: 3000
    targetPort: 80
    protocol: TCP
    nodePort: 30005
  type: NodePort
  selector:
    role: frontend
